"""
auto_coherency_check.py
========================
Automatically validates datasets generated by train_avus_kaggle.py generators.

Features:
  - Generates synthetic datasets on-the-fly
  - Validates them in real-time during generation
  - Stops generation if error rate exceeds threshold
  - Produces cleaned, validated datasets ready for training
  - Works with procedural infinite datasets (streaming validation)

Usage:
  # Validate existing generators
  python auto_coherency_check.py --validate-generators

  # Generate and validate a clean dataset
  python auto_coherency_check.py --generate --samples 1000 --output clean_dataset.txt

  # Stream-validate procedural dataset (checks as it generates)
  python auto_coherency_check.py --procedural --samples 10000 --difficulty 3
"""

import sys
import json
import random
import argparse
from pathlib import Path
from typing import List, Generator, Tuple
from coherency_checker import CoherencyChecker, CheckResult


# ══════════════════════════════════════════════════════════════════════════════
# INLINE DATASET GENERATORS (from train_avus_kaggle.py)
# ══════════════════════════════════════════════════════════════════════════════

def _rc(lst): return random.choice(lst)
def _ri(a, b): return random.randint(a, b)
def _rf(a, b): return round(random.uniform(a, b), 3)


def generate_3d_pairs(n: int = 10_000) -> List[str]:
    """3D object generation curriculum."""
    adjs = ["ancient","glowing","rusty","futuristic","crystalline","massive","tiny"]
    objs = ["rock","crystal","pillar","gateway","chest","statue","ruin","barrel"]
    prims = ["box","sphere","cylinder","torus"]
    mats  = ["stone","wood","metal","plastic"]
    out = []
    for _ in range(n):
        adj, obj = _rc(adjs), _rc(objs)
        prim, mat = _rc(prims), _rc(mats)
        params = {
            "object": obj, "primitive": prim, "material": mat,
            "scale": [_rf(0.5,3)]*3, "position": [_rf(-5,5)]*3,
            "roughness": _rf(0.1,0.9), "metallic": _rf(0,1) if mat=="metal" else 0.0,
        }
        text = (f"<|startoftext|>Generate a {adj} {obj} with {prim} shape "
                f"and {mat} material. [JSON_START]{json.dumps(params)}[JSON_END]"
                f"<|endoftext|>")
        out.append(text)
    return out


def generate_screen_action_pairs(n: int = 10_000) -> List[str]:
    """Screen action curriculum."""
    apps = ["Chrome","VS Code","Terminal","File Explorer","Discord"]
    btns = ["Submit","Cancel","Save","Login","Search","Next","Delete"]
    out = []
    for _ in range(n):
        x, y = _ri(10, 1910), _ri(10, 1070)
        btn  = _rc(btns)
        app  = _rc(apps)
        action = {"type": "click", "x": x, "y": y, "button": "left"}
        text = (f"<|startoftext|>{app} is open. "
                f"A '{btn}' button is at ({x},{y}). Click it. "
                f"[ACT_START]{json.dumps(action)}[ACT_END]<|endoftext|>")
        out.append(text)
    return out


def generate_language_pairs(n: int = 10_000) -> List[str]:
    """Language comprehension curriculum."""
    topics = [
        "machine learning", "neural networks", "transformers", "attention mechanisms",
        "gradient descent", "backpropagation", "reinforcement learning",
        "computer vision", "natural language processing", "robotics",
    ]
    templates = [
        "Explain {topic} in simple terms.",
        "What is {topic}?",
        "How does {topic} work?",
        "Describe the key concepts of {topic}.",
        "What are the applications of {topic}?",
    ]
    out = []
    for _ in range(n):
        topic    = _rc(topics)
        template = _rc(templates)
        question = template.format(topic=topic)
        answer   = f"{topic.capitalize()} is a fundamental concept in AI that involves processing and learning from data."
        text = f"<|startoftext|>{question} {answer}<|endoftext|>"
        out.append(text)
    return out


def generate_reasoning_pairs(n: int = 10_000) -> List[str]:
    """Reasoning and cognitive loop curriculum."""
    out = []
    for _ in range(n):
        a, b = _ri(1, 100), _ri(1, 100)
        op   = _rc(["+", "-", "*"])
        if op == "+":   result = a + b
        elif op == "-": result = a - b
        else:           result = a * b
        text = (f"<|startoftext|>Calculate: {a} {op} {b}. "
                f"Step 1: Identify the operation ({op}). "
                f"Step 2: Apply it. "
                f"Result: {result}<|endoftext|>")
        out.append(text)
    return out


# ══════════════════════════════════════════════════════════════════════════════
# STREAMING VALIDATION
# ══════════════════════════════════════════════════════════════════════════════

class StreamValidator:
    """Validates datasets as they're generated (infinite procedural support)."""

    def __init__(self, error_threshold: float = 0.05,
                 check_interval: int = 100,
                 auto_fix: bool = True):
        """
        Args:
            error_threshold: Stop if error rate exceeds this (0.05 = 5%)
            check_interval: Validate every N samples
            auto_fix: Attempt to fix common errors automatically
        """
        self.error_threshold = error_threshold
        self.check_interval = check_interval
        self.auto_fix = auto_fix

        self.total_generated = 0
        self.total_valid = 0
        self.total_errors = 0
        self.checker = CoherencyChecker()

    def validate_stream(self, generator: Generator[str, None, None],
                       max_samples: int = None) -> Generator[str, None, None]:
        """
        Validate samples from a generator as they're produced.
        Yields only valid samples.

        Args:
            generator: Generator yielding dataset entries
            max_samples: Stop after this many samples (None = infinite)

        Yields:
            Valid dataset entries
        """
        batch = []

        for sample in generator:
            self.total_generated += 1
            batch.append(sample)

            # Check batch periodically
            if len(batch) >= self.check_interval:
                valid_samples = self._validate_batch(batch)
                for valid in valid_samples:
                    yield valid
                batch = []

            # Stop if we hit error threshold
            if self.total_generated > 0:
                error_rate = self.total_errors / self.total_generated
                if error_rate > self.error_threshold:
                    print(f"\n[StreamValidator] Error threshold exceeded: "
                          f"{error_rate:.1%} > {self.error_threshold:.1%}")
                    print(f"[StreamValidator] Generated {self.total_generated} samples, "
                          f"{self.total_valid} valid, {self.total_errors} errors")
                    break

            # Stop if we hit max samples
            if max_samples and self.total_generated >= max_samples:
                break

        # Process remaining batch
        if batch:
            valid_samples = self._validate_batch(batch)
            for valid in valid_samples:
                yield valid

    def _validate_batch(self, batch: List[str]) -> List[str]:
        """Validate a batch of samples. Returns valid samples."""
        valid = []

        for sample in batch:
            # Quick validation
            result = self.checker.check_text(sample)

            errors = sum(1 for i in result.issues if i.severity == "error")

            if errors == 0:
                self.total_valid += 1
                valid.append(sample)
            else:
                self.total_errors += 1

                # Try auto-fix if enabled
                if self.auto_fix:
                    fixed = self._try_fix(sample, result)
                    if fixed:
                        # Re-validate
                        recheck = self.checker.check_text(fixed)
                        recheck_errors = sum(1 for i in recheck.issues
                                           if i.severity == "error")
                        if recheck_errors == 0:
                            self.total_valid += 1
                            self.total_errors -= 1  # Fixed the error
                            valid.append(fixed)

        return valid

    def _try_fix(self, sample: str, result: CheckResult) -> str:
        """Attempt to auto-fix common errors."""
        fixed = sample

        # Fix missing start token
        if not sample.startswith("<|startoftext|>"):
            fixed = "<|startoftext|>" + fixed

        # Fix missing end token
        if not sample.endswith("<|endoftext|>"):
            fixed = fixed + "<|endoftext|>"

        # Note: More complex fixes (JSON structure, math errors) are harder
        # to auto-fix without context, so we skip those

        return fixed if fixed != sample else None

    def stats(self) -> dict:
        """Return validation statistics."""
        error_rate = self.total_errors / max(1, self.total_generated)
        success_rate = self.total_valid / max(1, self.total_generated)

        return {
            "total_generated": self.total_generated,
            "total_valid": self.total_valid,
            "total_errors": self.total_errors,
            "error_rate": error_rate,
            "success_rate": success_rate,
        }


# ══════════════════════════════════════════════════════════════════════════════
# PROCEDURAL INFINITE DATASET GENERATOR
# ══════════════════════════════════════════════════════════════════════════════

def procedural_generator(difficulty: int = 1, seed: int = None) -> Generator[str, None, None]:
    """
    Infinite procedural dataset generator (like No Man's Sky).

    Args:
        difficulty: 1-5 (affects complexity of generated data)
        seed: Random seed for reproducibility

    Yields:
        Infinite stream of dataset entries
    """
    if seed is not None:
        random.seed(seed)

    generators = [
        generate_3d_pairs,
        generate_screen_action_pairs,
        generate_language_pairs,
        generate_reasoning_pairs,
    ]

    while True:
        # Pick a random generator type
        gen_func = _rc(generators)

        # Generate a batch
        batch_size = 100 * difficulty  # More difficult = larger batches
        batch = gen_func(batch_size)

        for sample in batch:
            yield sample


# ══════════════════════════════════════════════════════════════════════════════
# CLI
# ══════════════════════════════════════════════════════════════════════════════

def validate_generators():
    """Validate the built-in generators."""
    print("Validating built-in dataset generators...\n")

    generators = [
        ("3D Generation", generate_3d_pairs, 100),
        ("Screen Actions", generate_screen_action_pairs, 100),
        ("Language", generate_language_pairs, 100),
        ("Reasoning", generate_reasoning_pairs, 100),
    ]

    for name, gen_func, samples in generators:
        print(f"[{name}]")
        data = gen_func(samples)

        checker = CoherencyChecker()
        text = "\n".join(data)
        result = checker.check_text(text)

        errors = sum(1 for i in result.issues if i.severity == "error")
        warnings = sum(1 for i in result.issues if i.severity == "warning")

        print(f"  Samples: {samples}")
        print(f"  Valid: {result.valid_entries}/{result.total_entries}")
        print(f"  Success Rate: {(result.valid_entries/max(1,result.total_entries)*100):.1f}%")
        print(f"  Errors: {errors}, Warnings: {warnings}")
        print()


def generate_clean_dataset(samples: int, output: str):
    """Generate a validated clean dataset."""
    print(f"Generating {samples} clean samples...\n")

    # Generate mixed dataset
    generators = [
        ("3D", generate_3d_pairs),
        ("Screen", generate_screen_action_pairs),
        ("Language", generate_language_pairs),
        ("Reasoning", generate_reasoning_pairs),
    ]

    all_samples = []
    per_type = samples // len(generators)

    for name, gen_func in generators:
        print(f"  Generating {per_type} {name} samples...")
        batch = gen_func(per_type)
        all_samples.extend(batch)

    random.shuffle(all_samples)

    # Validate
    print("\nValidating...")
    checker = CoherencyChecker()
    text = "\n".join(all_samples)
    result = checker.check_text(text)

    # Filter out invalid entries
    valid_samples = []
    for i, sample in enumerate(all_samples, start=1):
        # Check if this line had errors
        line_errors = [issue for issue in result.issues
                      if issue.line_num == i and issue.severity == "error"]
        if not line_errors:
            valid_samples.append(sample)

    # Write output
    output_path = Path(output)
    output_path.write_text("\n".join(valid_samples))

    print(f"\n{'='*70}")
    print(f"Generated: {len(all_samples)} samples")
    print(f"Valid: {len(valid_samples)} samples ({len(valid_samples)/len(all_samples)*100:.1f}%)")
    print(f"Saved to: {output_path}")
    print(f"{'='*70}")


def stream_procedural_dataset(samples: int, difficulty: int, output: str = None):
    """Generate and stream-validate procedural dataset."""
    print(f"Generating procedural dataset (difficulty={difficulty})...\n")

    validator = StreamValidator(
        error_threshold=0.05,  # Stop if >5% error rate
        check_interval=100,    # Validate every 100 samples
        auto_fix=True          # Try to fix common errors
    )

    gen = procedural_generator(difficulty=difficulty, seed=42)
    valid_samples = []

    print("Streaming validation...")
    for i, sample in enumerate(validator.validate_stream(gen, max_samples=samples)):
        valid_samples.append(sample)

        if (i + 1) % 500 == 0:
            stats = validator.stats()
            print(f"  Generated: {stats['total_generated']} | "
                  f"Valid: {stats['total_valid']} | "
                  f"Errors: {stats['total_errors']} | "
                  f"Success: {stats['success_rate']:.1%}")

    # Final stats
    stats = validator.stats()
    print(f"\n{'='*70}")
    print(f"Procedural Generation Complete")
    print(f"{'='*70}")
    print(f"Generated: {stats['total_generated']}")
    print(f"Valid: {stats['total_valid']}")
    print(f"Errors: {stats['total_errors']}")
    print(f"Success Rate: {stats['success_rate']:.1%}")

    if output:
        output_path = Path(output)
        output_path.write_text("\n".join(valid_samples))
        print(f"Saved to: {output_path}")

    print(f"{'='*70}")


def main():
    parser = argparse.ArgumentParser(
        description="Auto-validate synthetic datasets for Janus training"
    )

    parser.add_argument("--validate-generators", action="store_true",
                       help="Validate all built-in generators")
    parser.add_argument("--generate", action="store_true",
                       help="Generate a clean validated dataset")
    parser.add_argument("--procedural", action="store_true",
                       help="Generate procedural infinite dataset with streaming validation")
    parser.add_argument("--samples", type=int, default=1000,
                       help="Number of samples to generate")
    parser.add_argument("--difficulty", type=int, default=1,
                       help="Difficulty level for procedural generation (1-5)")
    parser.add_argument("--output", type=str, default="clean_dataset.txt",
                       help="Output file path")

    args = parser.parse_args()

    if args.validate_generators:
        validate_generators()
    elif args.generate:
        generate_clean_dataset(args.samples, args.output)
    elif args.procedural:
        stream_procedural_dataset(args.samples, args.difficulty, args.output)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
