"""
avus_instruction_trainer.py
============================
Fine-tunes Avus on instruction-following data generated by
avus_instruction_dataset.py.

No API keys. No cloud services. Runs entirely locally on CPU or GPU.
Uses the existing Avus architecture from avus.py.

Usage:
    python avus_instruction_trainer.py
    python avus_instruction_trainer.py --epochs 5 --samples 100000
    python avus_instruction_trainer.py --resume --weights avus_instruct.pt
"""

from __future__ import annotations

import argparse
import gc
import json
import os
import sys
import time
from pathlib import Path
from typing import List, Optional, Set

import torch
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

# ── Path setup ────────────────────────────────────────────────────────────────

REPO_ROOT = Path(__file__).parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

# ── Tokenizer ─────────────────────────────────────────────────────────────────

SPECIAL_TOKENS: Set[str] = {
    "<|startoftext|>", "<|endoftext|>",
    "[INST]", "[/INST]",
}

class _Tokenizer:
    def __init__(self):
        try:
            import tiktoken
        except ImportError:
            os.system("pip install tiktoken -q")
            import tiktoken
        self._enc = tiktoken.get_encoding("gpt2")

    def encode(self, text: str) -> List[int]:
        return self._enc.encode(text, allowed_special=SPECIAL_TOKENS)

    def decode(self, tokens: List[int]) -> str:
        valid = [t for t in tokens if 0 <= t < self._enc.max_token_value]
        try:
            return self._enc.decode(valid)
        except Exception:
            return ""

    @property
    def vocab_size(self) -> int:
        return self._enc.max_token_value + 1


# ── Dataset ───────────────────────────────────────────────────────────────────

class InstructionDataset(Dataset):
    """
    Loads instruction pairs and tokenizes them for causal LM training.
    Uses loss masking: only compute loss on the response tokens, not the prompt.
    """

    def __init__(
        self,
        pairs: list,          # list of dicts with 'instruction' and 'response'
        tokenizer: _Tokenizer,
        block_size: int = 512,
    ):
        self.block_size = block_size
        self.tokenizer  = tokenizer
        self.data: List[tuple] = []  # (input_ids, labels)

        pad_id = tokenizer.encode("<|endoftext|>")[0]
        inst_start = tokenizer.encode("[INST]")[0]
        inst_end   = tokenizer.encode("[/INST]")[0]

        for pair in pairs:
            inst = pair.get("instruction", "")
            resp = pair.get("response", "")

            # Full sequence
            text = (
                f"<|startoftext|>[INST] {inst} [/INST]\n{resp}<|endoftext|>"
            )
            tokens = tokenizer.encode(text)

            # Find where response starts (after [/INST]\n)
            # Build prompt-only tokens to find the split point
            prompt_text = f"<|startoftext|>[INST] {inst} [/INST]\n"
            prompt_tokens = tokenizer.encode(prompt_text)
            prompt_len = len(prompt_tokens)

            # Chunk into block_size+1 windows
            idx = 0
            while idx < len(tokens):
                chunk = tokens[idx: idx + block_size + 1]
                if len(chunk) < 2:
                    break

                # Pad if needed
                if len(chunk) < block_size + 1:
                    chunk = chunk + [pad_id] * (block_size + 1 - len(chunk))

                input_ids = chunk[:-1]
                labels    = chunk[1:]

                # Mask prompt tokens in labels (set to -1 = ignore_index)
                # Only mask on the first chunk (where prompt lives)
                if idx == 0:
                    mask_end = min(prompt_len - 1, block_size)
                    labels = [-1] * mask_end + labels[mask_end:]

                self.data.append((
                    torch.tensor(input_ids, dtype=torch.long),
                    torch.tensor(labels,    dtype=torch.long),
                ))
                idx += block_size

        if not self.data:
            raise ValueError("Dataset is empty after tokenization.")

        print(f"[InstructionDataset] {len(self.data):,} sequences "
              f"(block_size={block_size})")

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]


# ── Training loop ─────────────────────────────────────────────────────────────

def train(
    epochs: int = 3,
    samples: int = 50_000,
    batch_size: int = 4,
    lr: float = 3e-5,
    block_size: int = 256,
    weights_in: Optional[str] = None,
    weights_out: str = "avus_instruct.pt",
    grad_accum: int = 4,
):
    gc.collect()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"\n[Trainer] Device: {device}")
    if device.type == "cuda":
        props = torch.cuda.get_device_properties(device)
        print(f"[Trainer] GPU: {props.name}  VRAM: {props.total_memory/1e9:.1f}GB")

    # ── Generate dataset ──
    print(f"\n[Trainer] Generating {samples:,} instruction pairs...")
    from avus_instruction_dataset import InstructionDatasetGenerator
    gen   = InstructionDatasetGenerator()
    pairs = gen.generate(samples=samples)
    pairs_dicts = [p.to_dict() for p in pairs]

    # ── Tokenizer ──
    tokenizer = _Tokenizer()
    print(f"[Trainer] Vocab size: {tokenizer.vocab_size:,}")

    # ── Load model ──
    from avus import Avus, AvusConfig

    # Use a config that matches the tokenizer vocab
    config = AvusConfig(
        vocab_size  = tokenizer.vocab_size,
        dim         = 384,
        n_layers    = 6,
        n_heads     = 6,
        n_kv_heads  = 3,
        max_seq_len = block_size,
        dropout     = 0.1,
    )

    model = Avus(config).to(device)

    # Load existing weights if provided
    if weights_in and Path(weights_in).exists():
        try:
            sd = torch.load(weights_in, map_location=device)
            sd = sd.get("model_state_dict", sd)
            model.load_state_dict(sd, strict=False)
            print(f"[Trainer] Loaded base weights from {weights_in}")
        except Exception as e:
            print(f"[Trainer] Could not load weights ({e}), training from scratch")
    else:
        print("[Trainer] Training from scratch (no base weights found)")

    total_params = sum(p.numel() for p in model.parameters())
    print(f"[Trainer] Parameters: {total_params:,}")

    # ── Dataset & loader ──
    dataset = InstructionDataset(pairs_dicts, tokenizer, block_size=block_size)
    loader  = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=0,
        pin_memory=(device.type == "cuda"),
    )

    # ── Optimizer ──
    optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=0.01)
    scaler    = torch.amp.GradScaler("cuda", enabled=(device.type == "cuda"))

    # ── Training ──
    best_loss  = float("inf")
    no_improve = 0

    for epoch in range(1, epochs + 1):
        model.train()
        epoch_loss = 0.0
        steps      = 0
        optimizer.zero_grad()
        t0 = time.time()

        for step, (x, y) in enumerate(loader):
            x, y = x.to(device), y.to(device)

            with torch.amp.autocast("cuda", enabled=(device.type == "cuda")):
                logits, _ = model(x)
                # Flatten and compute loss, ignoring -1 (masked prompt tokens)
                loss = F.cross_entropy(
                    logits.view(-1, logits.size(-1)),
                    y.view(-1),
                    ignore_index=-1,
                )
                loss = loss / grad_accum

            scaler.scale(loss).backward()

            if (step + 1) % grad_accum == 0:
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                scaler.step(optimizer)
                scaler.update()
                optimizer.zero_grad()

            epoch_loss += loss.item() * grad_accum
            steps += 1

            if steps % 100 == 0:
                elapsed = time.time() - t0
                print(f"  Epoch {epoch} | Step {steps}/{len(loader)} | "
                      f"Loss {epoch_loss/steps:.4f} | {elapsed:.0f}s elapsed")

        avg = epoch_loss / max(steps, 1)
        print(f"\nEpoch {epoch}/{epochs}  avg_loss={avg:.4f}  "
              f"time={time.time()-t0:.0f}s")

        # Save checkpoint
        model.save_checkpoint(weights_out)
        print(f"  Saved to {weights_out}")

        # LR decay on plateau
        if avg < best_loss:
            best_loss  = avg
            no_improve = 0
        else:
            no_improve += 1
            if no_improve >= 2 and lr > 1e-6:
                lr *= 0.5
                for g in optimizer.param_groups:
                    g["lr"] = lr
                print(f"  LR reduced to {lr:.2e}")
                no_improve = 0

    print(f"\n[Trainer] Done. Best loss: {best_loss:.4f}")
    print(f"[Trainer] Weights saved to: {weights_out}")
    return model


# ── Quick generation test ─────────────────────────────────────────────────────

def test_generation(weights_path: str, prompt: str = "What should I focus on to grow revenue?"):
    """Quick sanity check after training."""
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    tokenizer = _Tokenizer()

    from avus import Avus
    model = Avus.from_checkpoint(weights_path, device=str(device)).to(device)
    model.eval()

    full_prompt = f"<|startoftext|>[INST] {prompt} [/INST]\n"
    tokens = tokenizer.encode(full_prompt)
    idx    = torch.tensor([tokens], dtype=torch.long, device=device)

    with torch.no_grad():
        out = model.generate(idx, max_new_tokens=200, temperature=0.7, top_k=40)

    generated = tokenizer.decode(out[0][len(tokens):].tolist())
    print(f"\nPrompt: {prompt}")
    print(f"Response: {generated}")


# ── CLI ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train Avus on instruction data")
    parser.add_argument("--epochs",      type=int,   default=3)
    parser.add_argument("--samples",     type=int,   default=50_000)
    parser.add_argument("--batch-size",  type=int,   default=4)
    parser.add_argument("--lr",          type=float, default=3e-5)
    parser.add_argument("--block-size",  type=int,   default=256)
    parser.add_argument("--grad-accum",  type=int,   default=4)
    parser.add_argument("--weights-in",  type=str,   default=None,
                        help="Path to existing weights to fine-tune from")
    parser.add_argument("--weights-out", type=str,   default="avus_instruct.pt")
    parser.add_argument("--resume",      action="store_true",
                        help="Resume from avus_instruct.pt if it exists")
    parser.add_argument("--test",        action="store_true",
                        help="Run generation test after training")
    args = parser.parse_args()

    if args.resume and Path("avus_instruct.pt").exists():
        args.weights_in = "avus_instruct.pt"

    model = train(
        epochs     = args.epochs,
        samples    = args.samples,
        batch_size = args.batch_size,
        lr         = args.lr,
        block_size = args.block_size,
        weights_in = args.weights_in,
        weights_out= args.weights_out,
        grad_accum = args.grad_accum,
    )

    if args.test:
        test_generation(args.weights_out)
