# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nexus.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nexus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bnexus.proto\x12\x05nexus\x1a\x1bgoogle/protobuf/empty.proto\"5\n\x0cNexusCommand\x12\x14\n\x0c\x63ommand_type\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\"I\n\rNexusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x16\n\x0eresult_payload\x18\x03 \x01(\t\">\n\x10NexusStateUpdate\x12\x13\n\x0bupdate_type\x18\x01 \x01(\t\x12\x15\n\rstate_payload\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\x94\x01\n\x0cNexusService\x12;\n\x0e\x45xecuteCommand\x12\x13.nexus.NexusCommand\x1a\x14.nexus.NexusResponse\x12G\n\x12StreamStateUpdates\x12\x16.google.protobuf.Empty\x1a\x17.nexus.NexusStateUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nexus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NEXUSCOMMAND']._serialized_start=51
  _globals['_NEXUSCOMMAND']._serialized_end=104
  _globals['_NEXUSRESPONSE']._serialized_start=106
  _globals['_NEXUSRESPONSE']._serialized_end=179
  _globals['_NEXUSSTATEUPDATE']._serialized_start=181
  _globals['_NEXUSSTATEUPDATE']._serialized_end=243
  _globals['_EMPTY']._serialized_start=245
  _globals['_EMPTY']._serialized_end=252
  _globals['_NEXUSSERVICE']._serialized_start=255
  _globals['_NEXUSSERVICE']._serialized_end=403
# @@protoc_insertion_point(module_scope)
